import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { ExpressionsGeneratedModule, ExpressionsGeneratedSharedModule } from './generated/module';
import { ExpressionsValidationRegistry, ExpressionsValidator } from './expressions-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type ExpressionsAddedServices = {
    validation: {
        ExpressionsValidator: ExpressionsValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type ExpressionsServices = LangiumServices & ExpressionsAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const ExpressionsModule: Module<ExpressionsServices, PartialLangiumServices & ExpressionsAddedServices> = {
    validation: {
        ValidationRegistry: (services) => new ExpressionsValidationRegistry(services),
        ExpressionsValidator: () => new ExpressionsValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createExpressionsServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Expressions: ExpressionsServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        ExpressionsGeneratedSharedModule
    );
    const Expressions = inject(
        createDefaultModule({ shared }),
        ExpressionsGeneratedModule,
        ExpressionsModule
    );
    shared.ServiceRegistry.register(Expressions);
    return { shared, Expressions };
}
